### ISSUE TITLE
Why is it not working

### ISSUE THREAD

**Issue by Itachiirk** [chinoogawa/fbht#34]
Trying with python, python2, python3, 

Traceback (most recent call last):                                File "main.py", line 1, in <module>                               from mainFunc import privateMessageLink,sendRequestToList,setGlobalLogginng , \
  File "/home/hitachii/Hacking/fbht/mainFunc.py", line 5, in <module>
    import MyParser
  File "/home/hitachii/Hacking/fbht/MyParser.py", line 2, in <module>                                                               import simplejson as json
ImportError: No module named simplejson

**Comment by asep1407** [comment]
u need to install simplejson
